name: flutter_auth_buttons
description: Material buttons for logging into popular social networks, including Google, Facebook and Twitter.
version: 0.4.0
author: Duncan Jones <duncan@wortharead.com>
homepage: https://github.com/dmjones/flutter_auth_buttons

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - packages/flutter_auth_buttons/graphics/google-logo.png
    - packages/flutter_auth_buttons/graphics/flogo-HexRBG-Wht-100.png
    - packages/flutter_auth_buttons/graphics/Twitter_Logo_Blue.png
    - packages/flutter_auth_buttons/graphics/ms-symbollockup_mssymbol_19.png

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Medium.ttf
          weight: 500